### ISSUE TITLE
Lua error after update

### ISSUE THREAD

**Issue by thegrb93** [TwistedTail/ACF-3-Missiles#2]
[ACF - Updates] ACF-3-Missiles: Server is running on version Git-master-7c43dbe. No updates available, running on the latest version.

[ERROR] addons/acf-3/lua/acf/base/version/cl_version.lua:54: attempt to index local 'Branch' (a nil value)
  1. PrintStatus - addons/acf-3/lua/acf/base/version/cl_version.lua:54
   2. v - addons/acf-3/lua/acf/base/version/cl_version.lua:75
    3. unknown - lua/includes/modules/hook.lua:84

**Comment by TwistedTail** [comment]
Is this consistent? My first guess would be the network message not being sent correctly to the player since, [according to the wiki, it'll most likely fail if you don't give it a high enough delay.](https://wiki.facepunch.com/gmod/GM:PlayerInitialSpawn) It's already on the minimum suggested (5 seconds), so I suppose that could be the fault.

**Comment by thegrb93** [comment]
Seems every player that joined got the error spam.

**Comment by thegrb93** [comment]
I solved it for now by commenting out the hook.

**Comment by TwistedTail** [comment]
Noticed it's not actually ACF-Missiles but ACF itself the ones that's failing to get its branch. Are you using your own fork of it on the server?

**Comment by thegrb93** [comment]
Yeah, looks like it is.

**Comment by thegrb93** [comment]
I'm on this branch https://github.com/Stooberton/ACF-3/pull/41

**Comment by TwistedTail** [comment]
Fixed on https://github.com/Stooberton/ACF-3/commit/4c521b6a7153a1e95b06b76bb43555f1907e9041.
