### ISSUE TITLE
9m133 Wrong ingame name and lack of agility.

### ISSUE THREAD

**Issue by PolySteam** [TwistedTail/ACF-3-Missiles#4]
Agility of the 9m133 seems to be worse than even the SS40, The name in the menu is also wrong as it should be 9m133 not 9m113

**Comment by TwistedTail** [comment]
Noticed they would just fly at max speed even with minimal propellant aswell, probably related to the `ACF.DragDiv` change as we've been unable to test the Kornet during all this time.
I had the changes related to the wrong name and ID ready, but I have decided to not push them until I can fix the missile model (Kornets are only using their own missile model when loading it on the rack, the in-flight model is actually a Strela missile since the missile itself lacks an exhaust attachment).

**Comment by PolySteam** [comment]
Regarding the flight at max speed it probably has to do with the extremely high thrust when compared to the burnrate.

**Comment by TwistedTail** [comment]
It should be fine as of 0838256. There's two things to note though:
- The ID is still wrong, gonna fix this when I get to adapt the ammo crates to the new menu.
- Since the model still lacks the attachment required for the effect, the console will throw some warnings any time a Kornet is fired. Hopefully, this will be fixed once the new models arrive.
