### ISSUE TITLE
Inconsistent missile velocity orrrr some missiles being duds

### ISSUE THREAD

**Issue by xxxclaire1999** [TwistedTail/ACF-3-Missiles#45]
it seems that setting the propellant too low causes some missiles to be duds or just extremely slow

https://user-images.githubusercontent.com/84297432/118420961-a74b4180-b6f2-11eb-8f9e-b67b3b7a6c1a.mp4

https://user-images.githubusercontent.com/84297432/118420965-a9ad9b80-b6f2-11eb-8dfb-02bf77b9f841.mp4

**Comment by TwistedTail** [comment]
I don't see the issue with this, those missiles are just too slow and they're hitting the ground in front of your vehicle. They're not becoming duds either, you'd see them bounce around as props instead of exploding.

**Comment by LeninCat** [comment]
this behavior was noticed when i was testing the Type 63 RA.
workaround was to increase the StarterPercent to 0.9. then reduce the thrust so it doesn't consume the fuel fully before tickrate can accelerate them

**Comment by Alexandre425** [comment]
The correct solution would be to fix the missile code so that can't happen in the first place

https://github.com/TwistedTail/ACF-3-Missiles/blob/ff9eac9988f92d398423cb5d173f1f5c3f3226aa/lua/entities/acf_missile/init.lua#L225

If the fuel is expended in a single tick, I believe it will turn off the motor and set the thrust to 0 right away, before the force is applied. I can try fixing that.

**Comment by TwistedTail** [comment]
Fixed on 70a1344
